In [176]:
import scipy.io 


In [177]:
MNISTmini = scipy.io.loadmat('MNISTmini.mat')
MNISTmini

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Oct  8 18:13:47 2016',
 '__version__': '1.0',
 '__globals__': [],
 'train_fea1': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'train_gnd1': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [10],
        [10],
        [10]], dtype=uint8),
 'test_fea1': array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ..., 64,  0,  0],
        [ 0,  0,  0, ..., 25,  0,  0]], dtype=uint8),
 'test_gnd1': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [10],
        [10],
        [10]], dtype=uint8)}

In [178]:
import numpy as np
true_class = MNISTmini['train_gnd1']
test_fea_true_class = MNISTmini['test_gnd1']
true_class

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [10],
       [10],
       [10]], dtype=uint8)

In [179]:
true_class = true_class.flatten()
test_fea_true_class = test_fea_true_class.flatten()
true_class

array([ 1,  1,  1, ..., 10, 10, 10], dtype=uint8)

In [180]:
indexes = np.concatenate((np.where(true_class==5)[0], np.where(true_class==9)[0]))
test_fea_indeces = np.concatenate((np.where(test_fea_true_class==5)[0], np.where(test_fea_true_class==9)[0]))
indexes

array([24673, 24674, 24675, ..., 54074, 54075, 54076], dtype=int64)

In [181]:
imgs = MNISTmini['train_fea1']
test_fea = MNISTmini['test_fea1']
imgs


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [182]:
imgs_5_9 = []
true_label = []
test_fea_5_9 = []
test_true_label = []
for i in indexes:
    imgs_5_9.append(imgs[i])
    true_label.append(true_class[i])
imgs_5_9 = np.array(imgs_5_9)
true_label = np.array(true_label)

for i in test_fea_indeces:
    test_fea_5_9.append(test_fea[i])
    test_true_label.append(test_fea_true_class[i])
test_fea_5_9 = np.array(test_fea_5_9)
test_true_label = np.array(test_true_label)
imgs_5_9

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [183]:
## Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
clf = LogisticRegression(random_state=0).fit(imgs_5_9, true_label)

C:\Users\palac\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [186]:
clf.predict(test_fea_5_9)

array([5, 5, 5, ..., 9, 9, 9], dtype=uint8)

In [185]:
clf.score(test_fea_5_9, test_true_label)

0.9805365597054182